"""Dashboard adapter for the notebook-generated model registry.

The registry CSV is generated by the authoritative root notebook. This module
contains no model equation definitions; it reads and evaluates the registry
only for the dashboard's optional uploaded-data view.
"""
from __future__ import annotations

import ast
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = PROJECT_ROOT / "results" / "model_registry.csv"
if not REGISTRY_PATH.is_file():
    raise FileNotFoundError(
        "The notebook-generated model registry is missing. Run "
        "solar_radiation_analysis.ipynb with Restart Kernel and Run All first."
    )
MODEL_REGISTRY = pd.read_csv(REGISTRY_PATH).to_dict(orient="records")
MODEL_INFO = {row["model"]: (row["author"], row["equation"]) for row in MODEL_REGISTRY}
MODEL_IDS = [row["model"] for row in MODEL_REGISTRY]

_BINOPS = {
    ast.Add: lambda a, b: a + b,
    ast.Sub: lambda a, b: a - b,
    ast.Mult: lambda a, b: a * b,
    ast.Div: lambda a, b: a / b,
    ast.Pow: lambda a, b: a**b,
}
_UNARYOPS = {ast.UAdd: lambda a: a, ast.USub: lambda a: -a}
_FUNCTIONS = {"sqrt": np.sqrt, "ln": np.log, "log": np.log}


def _evaluate(node, values):
    if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
        return node.value
    if isinstance(node, ast.Name):
        if node.id in values:
            return values[node.id]
        if node.id in _FUNCTIONS:
            return _FUNCTIONS[node.id]
        raise ValueError(f"Unsupported name in registry equation: {node.id}")
    if isinstance(node, ast.BinOp) and type(node.op) in _BINOPS:
        return _BINOPS[type(node.op)](_evaluate(node.left, values), _evaluate(node.right, values))
    if isinstance(node, ast.UnaryOp) and type(node.op) in _UNARYOPS:
        return _UNARYOPS[type(node.op)](_evaluate(node.operand, values))
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in _FUNCTIONS and len(node.args) == 1:
        return _FUNCTIONS[node.func.id](_evaluate(node.args[0], values))
    raise ValueError(f"Unsupported syntax in registry equation: {ast.dump(node)}")


def predict_all(tmax, tmin, ra) -> pd.DataFrame:
    """Evaluate equations exported by the notebook for optional dashboard uploads."""
    tmax, tmin, ra = (pd.Series(v, dtype=float).reset_index(drop=True) for v in (tmax, tmin, ra))
    dt = (tmax - tmin).where(tmax > tmin)
    values = {"Tmax": tmax, "Tmin": tmin, "dT": dt, "DeltaT": dt,
              "Ra": ra, "Tmean": (tmax + tmin) / 2, "Theta": tmin / tmax}
    predictions = pd.DataFrame(index=tmax.index)
    with np.errstate(divide="ignore", invalid="ignore", over="ignore"):
        for row in MODEL_REGISTRY:
            expression = row["equation"].split(";", 1)[0].split("=", 1)[1].strip()
            expression = expression.replace("^", "**").replace("Tmax - Tmin", "dT").replace("Tmax-Tmin", "dT")
            predictions[row["model"]] = _evaluate(ast.parse(expression, mode="eval").body, values)
    return predictions


def registry_frame() -> pd.DataFrame:
    """Return the notebook-generated model registry as a DataFrame."""
    return pd.DataFrame(MODEL_REGISTRY)
